### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by UrbanSide** [ShahabGT/InstagramPicker#1]
`java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.app.ActionBar.setTitle(java.lang.CharSequence)' on a null object reference`

**Comment by ShahabGT** [comment]
hi, there was an error with actionbar now it's fixed use version 1.0.4

**Comment by UrbanSide** [comment]
@ShahabGT ,Thank you! Your library saved my nerves!
