### ISSUE TITLE
Limit setting

### ISSUE THREAD

**Issue by UrbanSide** [ShahabGT/InstagramPicker#3]
Your library is amazingly convenient.
You have no plans to make it possible to choose the min-max number of photos? It would be convenient not to cut in the user code.

**Comment by ShahabGT** [comment]
thank,
it will be available on the next update

**Comment by UrbanSide** [comment]
Thank you, I will really wait) For from everything I found here, your library saved the project)

**Comment by ShahabGT** [comment]
added in version 1.0.5
